# Generated by Django 4.2 on 2023-09-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structures', '0001_initial'),
        ('services', '0002_service_data_a_service_data_da_service_orario_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structures.structure')),
            ],
        ),
    ]
